### ISSUE TITLE
v0.0.2 Tracking

### ISSUE THREAD

**Issue by odecay** [fishfight/punchy#10]
For the next release our current priorities are 

- [x] - System ordering #9 
- [x] #13
- [x] #12
- [x] #11

**Comment by odecay** [comment]
I think we may be ready for a v0.0.2 release, the web-demo has been updated, please test and leave feedback here. https://fishfight.github.io/punchy/demo/

**Comment by erlend-sh** [comment]
Heh true, I noticed that too. Possibly throw in a pause in their attack pattern before release 🤷‍♂️

**Comment by odecay** [comment]
Sounds good I'll put some kind of delay in.

> That said you can still throw stuff at them and you can sneak around behind them and hit them sometimes, too, so it's not a big deal.

Hitting them from behind shouldn't really make a difference right now since the hotbox spawns right in the center of their body. Would probably be good to move it forward as well but I think that should be left for  #53

**Comment by erlend-sh** [comment]
Doneskies: https://github.com/fishfight/punchy/releases/tag/v0.0.2

Outstanding work all! 👏 ❤️
