### ISSUE TITLE
Ready for Fish Launcher

### ISSUE THREAD

**Issue by erlend-sh** [fishfight/punchy#103]
We’d like to initialize Punchy through https://github.com/fishfight/FishLauncher

We use a convention for release assets and they should follow this to work seamlessly with the launcher. Explained here: https://github.com/fishfight/FishFight/blob/main/PACKAGING.md#binary-releases

@orhun can answer any further questions.

**Comment by zicklag** [comment]
This should be trivial. Bevy games follow that exact convention by default.

I haven't looked at the launcher itself yet, but it should be nice and easy to integrate.

**Comment by zicklag** [comment]
After looking a little bit more into it, it seems like all we really need to do is setup a release pipeline on GitHub actions, very similar to this one from FishFight: https://github.com/fishfight/FishFight/blob/main/.github/workflows/release.yml.

Nuances such as dependencies, file names, and some similar things will be different, but it should be a straight-forward migration of that script.

**Comment by orhun** [comment]
Yup, eggxactly 🥚 I will take a look at the repository and adopt a similar workflow for release builds. It should be fairly straightforward.

**Comment by zicklag** [comment]
I'm closing this because I think that we've done everything we need to do on the Punchy side of this. Feel free to re-open if there's other stuff we need to do!
