### ISSUE TITLE
- Basic enemy AI/Behavior

### ISSUE THREAD

**Issue by odecay** [fishfight/punchy#12]
Enemies need to move + attack/interact with the player.
Might consist of pathfinding and an action queue for each enemy.

_further reading required_
https://github.com/zkat/big-brain - an AI plugin for bevy. I have not yet assessed it for our use case nor used it in any other projects but it seems like reasonable prior art to draw from.

**Comment by erlend-sh** [comment]
Two other AI library candidates:
https://github.com/PsichiX/emergent
https://github.com/ethz-gtc/npc-engine

**Comment by erlend-sh** [comment]
Worth noting that the libraries we’ve listed aren’t really relevant to *basic* AI. This issue will be considered resolved by a very simple ‘go to player position and attack’ system.

**Comment by odecay** [comment]
The beginnings of this are in as of https://github.com/fishfight/punchy/commit/f16b7bb6422cd415f9acb6a1f30ab8fb23bf46f9. It has implications for the player, since now they can be attacked and the players state and player controller dont account for any hit state currently. Will get to those next.

**Comment by odecay** [comment]
This needs some checks to keep the enemies in bounds, right now they can walk out of map if player happens to be close to edge.

**Comment by odecay** [comment]
I think I'm calling this closed for now but there are still improvements to be done. In #29 targeting system will need to be updated to better account for more than 1 player.  This has also brought to light the necessity of
