### ISSUE TITLE
Setup Bors PR Merge Bot

### ISSUE THREAD

**Issue by zicklag** [fishfight/punchy#124]
### Description

We'll probably want to use Bors for merging pull requests. It's simple to setup and I can do it if we want to.

The goal is to make sure that everything that gets merged to master has actually passed CI in it's exact state. As it stands, if we merge multiple pull requests off of master, even if each branch passed CI, we don't know that the _combination_ of the pull requests will pass CI once they are merged to master.

I'd like to hear thoughts form @odecay and @erlend-sh if you guys have any input.

### Alternatives & Prior Art

See this comment for background: https://github.com/fishfight/punchy/pull/111#pullrequestreview-1048578729.

**Comment by 64kramsystem** [comment]
I'm a big fan of Bors. Actually, my regret is that it doesn't support private repositories :smile:

**Comment by 64kramsystem** [comment]
I think this needs to be done by somebody in the fighfight organization.

**Comment by 64kramsystem** [comment]
ok, reassigning again. now I have the power™ :joy:
