### ISSUE TITLE
Flop sound effect does not play for Sharky

### ISSUE THREAD

**Issue by odecay** [fishfight/punchy#130]
### Description
Flop sound effect does not play for Sharky

### To Reproduce

Start game,  Press ,/< key to execute P2 flop attack, flop sound effect does not play.

### Expected Behavior

Expect flop sfx to play for P2

**Comment by 64kramsystem** [comment]
I've added the sound. Generally speaking, when I implement functionalities that work on assets, I add just the minimum required, leaving the configuration of the real assets to people working on design.
