### ISSUE TITLE
Exiting Pause menu behaves unexpectedly

### ISSUE THREAD

**Issue by odecay** [fishfight/punchy#131]
### Description

Exiting pause menu returns the player to the main menu, abandoning in progress gameplay.
This is not the desired behavior either for gameplay or debugging purposes. Ideally for gameplay exiting pause state would return the players to in progress session.
For debugging it is useful to not have the current world despawned while the pause is taking place, so that entities and components can be inspected using bevy-inspector-egui.

### To Reproduce

Pause the game, exit pause menu by pressing ESC key or Continue menu button.

**Comment by zicklag** [comment]
Just went though the git history and found this was introduced by e49b2e8b10be888316634a0030955fc186f7b58c.

**Comment by zicklag** [comment]
I'll fix this one, I think I have an idea for a clean solution.

**Comment by 64kramsystem** [comment]
> Just went though the git history and found this was introduced by [e49b2e8](https://github.com/fishfight/punchy/commit/e49b2e8b10be888316634a0030955fc186f7b58c).

:exploding_head:
