### ISSUE TITLE
Players Can't Walk Left

### ISSUE THREAD

**Issue by zicklag** [fishfight/punchy#141]
### Description

Not sure why yet, but players can't walk left.

### To Reproduce

Start the game and try to press the left arrow button.

### Expected Behavior

Sharky should walk left.

### Additional Context

This was introduced relatively recently, not sure what commit yet.

**Comment by 64kramsystem** [comment]
Can't reproduce it! (commit 447c69aa6afd81d40d179fa03e72f07bbf3172c6).

**Comment by zicklag** [comment]
Whoa, now it's not happening. I must have done something weird.
