### ISSUE TITLE
Further updates to CI

### ISSUE THREAD

**Issue by 64kramsystem** [fishfight/punchy#145]
### Description

Discussions gathered around:

-  ~~CI check for debug features to the matrix (144)~~
- run the clippy check as a matrix on different platforms to capture differences in the build path on different platforms (since Bevy handles the abstraction over desktop platforms, we'd be good just checking Linux and web)

**Comment by 64kramsystem** [comment]
@odecay @zicklag collecting the next round of updates here.

**Comment by odecay** [comment]
#144 it seems like we are settling on the idea of removing the debug features and implementing them instead as runtime config option.
