### ISSUE TITLE
Update to Bevy 0.8.0

### ISSUE THREAD

**Issue by zicklag** [fishfight/punchy#176]
### Description

Bevy 0.8.0 was just released. It'd probably be good to update as soon as we can. We've already got dependencies such as leafwing that we have to use a Bevy 0.7.0 backport for, so even if we have to use forks for some dependencies like Bevy Egui until 0.8.0 support is merged it might not be any worse than where we are at with our dependencies now.

Updating might help us with scripting support, depending on how much we might be able to use [bevy_mod_js_scriptin](https://github.com/jakobhellermann/bevy_mod_js_scripting) which is built on Bevy 0.8.0.

I'll probably try to port our stuff to Bevy 0.8 and see how difficult it will be so we can decide when we want to do that for sure.

**Comment by odecay** [comment]
I agree with updating to 0.8 asap. 
I know Loopless and LWIM both already have branches with support for bevy main.
I guess we'd be waiting on/have to update Bevy Egui

**Comment by zicklag** [comment]
Yep, along with Bevy inspector egui, which also has dependencies on rapier.

I suppose I'll just start opening pull requests. :D

**Comment by odecay** [comment]
> Yep, along with Bevy inspector egui, which also has dependencies on rapier.
> 
> I suppose I'll just start opening pull requests. :D
> 
> Looks like rapier is the deepest dep and should be updated first.
https://github.com/dimforge/bevy_rapier/pull/219

**Comment by zicklag** [comment]
> https://github.com/dimforge/bevy_rapier/pull/219

Thank you!

---

So, as I keep looking, this ends up pretty deep, when we need new releases all the way down to `nalgebra`, so I think it's probably better for us just to wait for some of those PRs to be merged than to try and make some git dependencies working, because keeping them up-to-date will be a pain as different maintainers may ask for changes.

That doesn't mean we can't submit PRs for the projects that don't already have them, though, and wait for those to get releases before we update.

I don't need Bevy 0.8 for the scripting MVP, either, so we aren't blocked by it just yet.

**Comment by 64kramsystem** [comment]
I don't have any opinion on this, so... enjoy :smile:

**Comment by zicklag** [comment]
Hey, I just found out why Punchy was depending on crates like `bevy_pbr` and `bevy_gltf`, even though we shouldn't have needed it. They were dependencies of `bevy-parallax`. I'll fix that in my PR to update it to Bevy 0.8.

**Comment by odecay** [comment]
> So, as I keep looking, this ends up pretty deep, when we need new releases all the way down to `nalgebra`, so I think it's probably better for us just to wait for some of those PRs to be merged than to try and make some git dependencies working

The nalgebra change is already merged, but your right its not yet released.

**Comment by erlend-sh** [comment]
> bevy-parallax

All Punchy devs should have push access to this repo, so lemme know if you don’t.

**Comment by odecay** [comment]
[bevy_rapier is updated](https://github.com/dimforge/bevy_rapier/releases/tag/v0.16)

**Comment by zicklag** [comment]
Wow, that was fast! Cool. That might get us far enough to use git dependencies for the rest. I'll be trying that out soon.

**Comment by zicklag** [comment]
I've got a working PR to update Bevy Parallax: https://github.com/Corrosive-Games/bevy-parallax/pull/10

**Comment by zicklag** [comment]
Finished in #189 .
