### ISSUE TITLE
Basic Editor

### ISSUE THREAD

**Issue by erlend-sh** [fishfight/punchy#185]
### Description

*Just thinking out loud; longer-term project* 

Some minimal editor features would be a nice addition to our modding story started by #107.

We’re already using egui, and [bevy_editor_pls](https://github.com/jakobhellermann/bevy_editor_pls) by @jakobhellermann is also egui-based. We also rewrote the original Fish Fight editor in egui.

Would we gain any useful dev powers by building an editor sooner rather than later?

### Alternatives & Prior Art

- https://github.com/fishfight/FishFight/pull/407

**Comment by odecay** [comment]
#26
