### ISSUE TITLE
Egui World Inspector

### ISSUE THREAD

**Issue by zicklag** [fishfight/punchy#21]
Do we want to add the Egui world inspector plugin that could be displayed, for instance, when pressing F12. It can be quite handy.

https://github.com/jakobhellermann/bevy-inspector-egui

Probably only enabled when built with a `debug` feature flag.

**Comment by odecay** [comment]
Yea I've found using bevy-egui-inspector as a debug feature really useful for debugging/making sure things are working as expected.
