### ISSUE TITLE
First audio pass

### ISSUE THREAD

**Issue by erlend-sh** [fishfight/punchy#55]
For game music we've already got a completed OST that can be reused as-is for this game:
https://spicylobster.itch.io/fish-world-pack

We'll probably follow up with a beatemup-tailored remix of this album way later.

For SFX, anything creative-commons is on the table for the purpose of temporary use. A [quick search for 'punch'](https://opengameart.org/art-search-advanced?keys=punch&title=&field_art_tags_tid_op=or&field_art_tags_tid=&name=&field_art_type_tid%5B%5D=13&field_art_licenses_tid%5B%5D=17981&field_art_licenses_tid%5B%5D=2&field_art_licenses_tid%5B%5D=17982&field_art_licenses_tid%5B%5D=3&field_art_licenses_tid%5B%5D=6&field_art_licenses_tid%5B%5D=5&field_art_licenses_tid%5B%5D=10310&field_art_licenses_tid%5B%5D=4&field_art_licenses_tid%5B%5D=8&field_art_licenses_tid%5B%5D=7&sort_by=score&sort_order=DESC&items_per_page=24&Collection=) resulted in these two which I quite like:
https://opengameart.org/content/punch-slap-n-kick
https://opengameart.org/content/37-hitspunches

Also:
https://www.kenney.nl/assets/interface-sounds
https://www.kenney.nl/assets/ui-audio

**Comment by 64kramsystem** [comment]
Do we go for `bevy_kira_audio` for audio?

**Comment by erlend-sh** [comment]
It appears to be the default solution for audio in Bevy right now, so yeah 👍

**Comment by zicklag** [comment]
Yeah, it's nice and easy to use. I ran into a couple limitations around wanting to fade music in and out, but I know how to implement it and they said they were open to a PR, so I'll get to that eventually.

**Comment by 64kramsystem** [comment]
Working on this.
