### ISSUE TITLE
Unify (if possible) the player translation (and limits)

### ISSUE THREAD

**Issue by 64kramsystem** [fishfight/punchy#63]
Currently, there is separate logic to handle the player translation, for example, on user input vs. attacks.

Such logic should be merged; otherwise, additional translation processing (currently, limits) would need to be applied for each point where translations are manipulated.

A standard pattern for this is all movements should send an event, which is then processed, and applied (according to the rules).

When this is implemented, remove the `dir.x < 0.` condition from the `player_controller` system.

I see this as depending on #99, so it'll be clear which systems handle translation, and how they need to be modified (it's known already which they are, but it's confusing to operate right now, since we'd need to introduce some temporal dependency).

**Comment by odecay** [comment]
Moving this to v0.0.4 but if anyone disagrees feel free to move it back.

**Comment by 64kramsystem** [comment]
> Moving this to v0.0.4 but if anyone disagrees feel free to move it back.

It makes sense to do it for 0.0.4 (because in order to do it in a very clean way, I think it requires stages in place), however, I've thought of an easy preliminary way to do it, so that we can start fixing those pesky out-of-border movements we have now :smile: 

In case I'll complete this in time for 0.0.3, I'll just create the PR and change the milestone.

**Comment by odecay** [comment]
Sounds good, the stage reorder was my motivation for moving to v0.0.4 also. :+1:
