### ISSUE TITLE
Add basic mob sprites

### ISSUE THREAD

**Issue by odecay** [fishfight/punchy#8]
We have more enemy variants which need to be added to the game.

- [x] Slinger Variants
- [x] Bandit Variants
- [x] Brute YAML definition and its Variants

**Comment by zicklag** [comment]
Just a note for anybody finding this issue: now all of the player/enemy types are implemented with YAML, for example the [bandit](https://github.com/fishfight/punchy/tree/master/assets/fighters/bandit). So this issue is now very approachable for non-programmers! :)

**Comment by edgarssilva** [comment]
Does the current yaml system support nested folders inside the fighters? Since we have multiple variants of the same "type" I was thinking we could have something like:

fighters
 - jerk  
     - jerk1
     - jerk2
     - jerk3
  - bandit
    - bandit1
    - bandit2
    - bandit3
   
Another alternative is to have multiple sprite sheets for each fighter in the yaml and choose one randomly.

**Comment by odecay** [comment]
I feel like we should introduce some concept of variants for spritesheets when its the same enemy "type" rather than giving them all unique definitions. Although maybe in the future the different variants will have different gameplay implications, but we can get to that if it comes up.

**Comment by edgarssilva** [comment]
Could I just turn the image proprety into an array and just randomly select one image path?

**Comment by zicklag** [comment]
If we're good choosing them randomly for now, it seems like making the image an array is a good idea.

**Comment by zicklag** [comment]
That is a little strange. Maybe try adding loop index to the label and see if that resolves the issue. So the label would end up being `atlas0`, `atlas1`, and so on.

**Comment by edgarssilva** [comment]
> That is a little strange. Maybe try adding loop index to the label and see if that resolves the issue. So the label would end up being `atlas0`, `atlas1`, and so on.

Still no luck :/
