### ISSUE TITLE
Update Readme Video

### ISSUE THREAD

**Issue by zicklag** [fishfight/punchy#90]
We've gotten some new stuff in now, it seems like we could update the video.

**Comment by erlend-sh** [comment]
On a related note, I’ve added the game to Bevy Assets: https://github.com/bevyengine/bevy-assets/pull/222

![0A889D7E-8A00-4F6F-A191-A6C2A10C4DA9](https://user-images.githubusercontent.com/583842/179758081-34e04690-95fb-42fe-bdac-3a557ca49425.jpeg)

I’ll update it with a mid-jump bossman when that’s in ;)

**Comment by odecay** [comment]
Done in 8c41bf2e7d35c5b862b0715da9c209d9c277924b
