### ISSUE TITLE
Program doesn't return to main menu when players lose

### ISSUE THREAD

**Issue by 64kramsystem** [fishfight/punchy#96]
When the players lose, the program doesn't return to the main menu (currently, it crashes).

While it's probably intended right now not to spend effort on this, I think it'd be nice to just return to the main menu on game over. This may (not 100% sure) have also some architectural consequences, if it requires some cleanup to be designed/implemented (which I think is g00d).

**Comment by zicklag** [comment]
We've already had to clean up things when going back to the main menu from the pause menu. So far it works just to despawn every entity other than the camera, if I remember right. Either way we can take reference for how that worked.

**Comment by 64kramsystem** [comment]
I'm fixing two crashes right now - those shouldn't happen in any case (they've been introduced by the camera movement).

**Comment by 64kramsystem** [comment]
I've renamed this issue; fixing the panics was trivial, but I think it's still worth tracking the fact that the game should at least return to the main menu for now.
